# Generated by Django 6.0.3 on 2026-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin')], default='reader', max_length=10),
        ),
    ]
